management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URL:http://localhost:8761/eureka}
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    hostname: localhost
    preferIpAddress: true