spring:
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/identity/**
        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/profile/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification/**
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/post/**
        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/chat/**
        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/search/**
        - id: timeline-service
          uri: lb://timeline-service
          predicates:
            - Path=/timeline/**
server:
  port: 8080
#management:
#  tracing:
#    enabled: true
#    sampling:
#      rate: 1.0
#  zipkin:
#    tracing:
#      endpoint: http://localhost:9411/api/v2/spans