server:
  port: ${POST_SERVICE_PORT:9004}
  servlet:
    context-path: /post
spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:root@localhost:27017/post_service?authSource=admin}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    timeout: 60000
  cache:
    type: redis
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
      profile-service:
        url: ${PROFILE_SERVICE_URL:http://localhost:9002/profile}