server:
  port: ${PROFILE_SERVICE_PORT:9002}
  servlet:
    context-path: /profile
spring:
  # kafka:
  #   bootstrap-servers: "${HOST_IP_ADDRESS:localhost}:9092"
  #   consumer:
  #     group-id: ${KAFKA_GROUP_ID:default-group}
  neo4j:
    uri: ${NEO4J_URI:bolt://localhost:7687}
    authentication:
      username: ${NEO4J_USERNAME:neo4j}
      password: ${NEO4J_PASSWORD:12345678}