server:
  port: 9002
  servlet:
    context-path: /profile
spring:
  #  kafka:
  #    bootstrap-servers: "${HOST_IP_ADDRESS:localhost}:9092"
  #    consumer:
  #      group-id: ${KAFKA_GROUP_ID:default-group}
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 12345678