server:
  port: ${SOCKET_SERVICE_PORT:9006}
spring:
  kafka:
    bootstrap-servers: "${KAFKA_SERVERS:localhost:9094}"
    consumer:
      chat-group-id: ${KAFKA_CHAT_GROUP_ID:chat-group}
      notification-group-id: ${KAFKA_NOTIFICATION_GROUP_ID:notification-group}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "*"
