server:
  port: ${TIMELINE_SERVICE_PORT:9697}
  servlet:
    context-path: /timeline
spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    timeout: 60000
  cache:
    type: redis
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
      profile-service:
        url: ${PROFILE_SERVICE_URL:http://localhost:9002/profile}