server:
  port: ${TIMELINE_SERVICE_PORT:9697}
  servlet:
    context-path: /timeline
spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    timeout: 60000
  cache:
    type: redis